import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import Link from "next/link";
import typenice from "../../public/typenice.png";
import Image from "next/image";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "음악 AK - 47",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="ko">
      <head>
        <link
          href="//spoqa.github.io/spoqa-han-sans/css/SpoqaHanSansNeo.css"
          rel="stylesheet"
          type="text/css"
        ></link>
      </head>
      <body>
        <div className="navbar">
          <Link href={"/"}>
            <Image src={typenice} alt="Logo" width={32} height={32} />
          </Link>
          <Link href={"/components"}>로그인 &nbsp; 회원가입</Link>
        </div>
        {children}
      </body>
      <div className="footer">
        <p>푸터</p>
      </div>
    </html>
  );
}
